-- Future 5.0 SaaS launch schema
-- Run this in Supabase SQL Editor once. Safe to re-run.
create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan text not null default 'free' check (plan in ('free','personal','pro','business')),
  status text not null default 'active',
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('ai_message','web_search')),
  model text,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  estimated_cost_usd numeric(12,6) not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists usage_events_user_created_idx on public.usage_events(user_id, created_at desc);

create table if not exists public.user_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- Web Push subscriptions are server-managed. user_id may be null for guest/public-beta devices.
create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists push_subscriptions_user_idx on public.push_subscriptions(user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'display_name', split_part(coalesce(new.email,''),'@',1)))
  on conflict (id) do nothing;
  insert into public.subscriptions (user_id, plan, status)
  values (new.id, 'free', 'active') on conflict (user_id) do nothing;
  insert into public.user_state (user_id, state)
  values (new.id, '{}'::jsonb) on conflict (user_id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.usage_events enable row level security;
alter table public.user_state enable row level security;
alter table public.push_subscriptions enable row level security;

drop policy if exists "profile self read" on public.profiles;
create policy "profile self read" on public.profiles for select using (auth.uid() = id);
drop policy if exists "profile self update" on public.profiles;
create policy "profile self update" on public.profiles for update using (auth.uid() = id);

drop policy if exists "subscription self read" on public.subscriptions;
create policy "subscription self read" on public.subscriptions for select using (auth.uid() = user_id);

drop policy if exists "usage self read" on public.usage_events;
create policy "usage self read" on public.usage_events for select using (auth.uid() = user_id);

drop policy if exists "state self read" on public.user_state;
create policy "state self read" on public.user_state for select using (auth.uid() = user_id);
drop policy if exists "state self insert" on public.user_state;
create policy "state self insert" on public.user_state for insert with check (auth.uid() = user_id);
drop policy if exists "state self update" on public.user_state;
create policy "state self update" on public.user_state for update using (auth.uid() = user_id);

-- No browser policy for push_subscriptions: API routes use the service-role key.
