"use client";
import { useEffect,useState } from "react";

type DeferredInstall=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};
export default function InstallPage(){
 const [installPrompt,setInstallPrompt]=useState<DeferredInstall|null>(null);const [installed,setInstalled]=useState(false);const [permission,setPermission]=useState("default");const [message,setMessage]=useState("");
 useEffect(()=>{setInstalled(window.matchMedia("(display-mode: standalone)").matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone));setPermission("Notification" in window?Notification.permission:"unsupported");const handler=(e:Event)=>{e.preventDefault();setInstallPrompt(e as DeferredInstall)};window.addEventListener("beforeinstallprompt",handler);navigator.serviceWorker?.register("/sw.js");return()=>window.removeEventListener("beforeinstallprompt",handler)},[]);
 async function install(){if(installPrompt){await installPrompt.prompt();const result=await installPrompt.userChoice;if(result.outcome==="accepted")setInstalled(true);setInstallPrompt(null);return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);setMessage(ios?"iPhone/iPad: open this page in Safari → tap Share → Add to Home Screen → Add.":"Open the browser menu and choose Install app / Add to Home screen.")}
 async function notifications(){if(!("Notification" in window)){setMessage("Notifications are not supported by this browser.");return}const result=await Notification.requestPermission();setPermission(result);if(result!=="granted"){setMessage("Notification permission was not granted.");return}const reg=await navigator.serviceWorker.register("/sw.js");await reg.showNotification("Future is ready",{body:"Notifications are enabled on this device.",icon:"/icon-192.png",tag:"future-ready"});setMessage("Notifications enabled. Future can now receive background web-push alerts when the server sends them.")}
 return <main className="futureDownloadPage"><section className="futureDownloadHero"><div className="futureDownloadOrb"/><div className="futureEyebrow">FUTURE · YOUR AI SECRETARY</div><h1>Future on your phone.</h1><p>Install Future like an app, then enable notifications for reminders and alerts. Galaxy uses pure black and warm yellow across desktop and mobile.</p></section><section className="futureInstallPanel"><div className="futureInstallStatus"><span>DEVICE STATUS</span><strong>{installed?"Installed / standalone":"Browser mode"}</strong><b>{permission==="granted"?"Notifications ON":"Notifications "+permission}</b></div><div className="futureInstallSteps"><article><span>1</span><div><h2>Install Future</h2><p>Android/Chrome can show an install prompt. On iPhone, use Safari → Share → Add to Home Screen.</p></div><button onClick={install}>{installed?"Installed":"Install Future"}</button></article><article><span>2</span><div><h2>Enable notifications</h2><p>Permission must be granted on this device. iPhone web push requires Future to be installed on the Home Screen.</p></div><button onClick={notifications} disabled={permission==="unsupported"}>{permission==="granted"?"Test notification":"Enable notifications"}</button></article><article><span>3</span><div><h2>Background alerts</h2><p>The service worker is prepared for Web Push, so notifications can arrive without keeping the Future page open once the server push subscription/sender is configured.</p></div></article></div>{message&&<div className="futureInstallMessage">{message}</div>}<div className="futureInstallNote"><strong>Important:</strong> spoken voice from the webpage itself cannot be guaranteed after Safari/Chrome is fully closed. Background Web Push can still show a system notification and play the notification sound allowed by the phone.</div></section><footer className="futureDownloadFooter"><a href="/">Open Future</a><a href="/privacy">Privacy</a><a href="/alerts-safety">Alerts & safety</a></footer></main>
}
