const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
function load(file,deps={},extra={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:n=>deps[n],Buffer,URL,...extra});return exports;}
const anon='header.'+Buffer.from(JSON.stringify({role:'anon'})).toString('base64url')+'.signature';
function config(env){return load('lib/supabase/config.ts',{}, {process:{env}}).getPublicSupabaseConfig()}
test('PUBLIC variables configure auth without NEXT_PUBLIC',()=>assert.ok(config({PUBLIC_SUPABASE_URL:'https://fixture.supabase.co',PUBLIC_SUPABASE_ANON_KEY:anon})));
test('legacy NEXT_PUBLIC variables remain supported',()=>assert.ok(config({NEXT_PUBLIC_SUPABASE_URL:'https://fixture.supabase.co',NEXT_PUBLIC_SUPABASE_ANON_KEY:anon})));
test('never return service-role or secret keys from public config',()=>{for(const key of ['sb_secret_fixture','header.'+Buffer.from(JSON.stringify({role:'service_role'})).toString('base64url')+'.sig',anon])assert.equal(config({PUBLIC_SUPABASE_URL:'https://fixture.supabase.co',PUBLIC_SUPABASE_ANON_KEY:key,SUPABASE_SERVICE_ROLE_KEY:key}),null)});
test('malformed and missing configuration fail closed',()=>{assert.equal(config({}),null);assert.equal(config({PUBLIC_SUPABASE_URL:'javascript:alert(1)',PUBLIC_SUPABASE_ANON_KEY:anon}),null)});
test('async client coalesces concurrent config requests',async()=>{let requests=0,clients=0;const instance={auth:{}};const c=load('lib/supabase/client.ts',{'@supabase/ssr':{createBrowserClient:()=>{clients++;return instance}}},{fetch:async()=>{requests++;return {ok:true,json:async()=>({configured:true,url:'https://fixture.supabase.co',anonKey:anon})}}});const [a,b]=await Promise.all([c.createClient(),c.createClient()]);assert.equal(a,b);assert.equal(requests,1);assert.equal(clients,1)});
test('async client retries after config request failure',async()=>{let requests=0;const c=load('lib/supabase/client.ts',{'@supabase/ssr':{createBrowserClient:()=>({auth:{}})}},{fetch:async()=>({ok:++requests>1,json:async()=>({configured:true,url:'https://fixture.supabase.co',anonKey:anon})})});assert.equal(await c.createClient(),null);assert.ok(await c.createClient())});
