"use client";
import { useEffect, useState } from "react";

type Props={paid:boolean;onClose?:()=>void};
const KEY="future.layout.v2";
const FREE_THEMES=new Set(["lavender","galaxy","sky"]);
export default function CustomizeLayoutPanel({paid}:Props){
 const [theme,setTheme]=useState("lavender"); const [density,setDensity]=useState("comfortable"); const [layout,setLayout]=useState("classic");
 const [bgScope,setBgScope]=useState("none"); const [bgPreset,setBgPreset]=useState("none"); const [bgImage,setBgImage]=useState("");
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);setTheme(x.theme==="dark"?"galaxy":(x.theme||"lavender"));setDensity(x.density||"comfortable");setLayout(x.layout||"classic");setBgScope(x.bgScope||"none");setBgPreset(x.bgPreset||"none");setBgImage(x.bgImage||"");apply(x)}}catch{}},[]);
 function apply(x:any){const t=x.theme==="dark"?"galaxy":(x.theme||"lavender");document.documentElement.dataset.futureTheme=t;document.documentElement.dataset.futureDensity=x.density||"comfortable";document.documentElement.dataset.futureLayout=x.layout||"classic";document.documentElement.dataset.futureBgScope=x.bgScope||"none";document.documentElement.dataset.futureBgPreset=x.bgPreset||"none"; if(x.bgImage)document.documentElement.style.setProperty("--future-user-bg",`url(${x.bgImage})`);else document.documentElement.style.removeProperty("--future-user-bg")}
 function save(next:any){const x={theme,density,layout,bgScope,bgPreset,bgImage,...next};if(!paid&&!FREE_THEMES.has(x.theme))x.theme="lavender";if(!paid){x.density="comfortable";x.layout="classic";x.bgScope="none";x.bgPreset="none";x.bgImage=""}setTheme(x.theme);setDensity(x.density);setLayout(x.layout);setBgScope(x.bgScope);setBgPreset(x.bgPreset);setBgImage(x.bgImage);localStorage.setItem(KEY,JSON.stringify(x));apply(x)}
 function upload(file?:File){if(!paid||!file)return; if(!file.type.startsWith("image/"))return; const r=new FileReader();r.onload=()=>save({bgImage:String(r.result||""),bgPreset:"upload"});r.readAsDataURL(file)}
 return <div className="v42Customize"><div className="v42CustomizeIntro"><h3>Customize Future</h3><p>Free users can choose three color themes. Paid users can also change layout, density and use a full-page or calendar background.</p></div>
 <section><h4>Color theme <span className="v42FreeBadge">FREE</span></h4><div className="v42ThemeChoices">{[["lavender","Lavender"],["galaxy","Galaxy"],["sky","Sky"]].map(([v,l])=><button key={v} className={theme===v?"selected":""} onClick={()=>save({theme:v})}><i className={`swatch ${v}`}/>{l}</button>)}</div></section>
 <section className={!paid?"lockedSection":""}><div className="v42SectionHead"><h4>Paid customization</h4>{!paid&&<a href="/pricing">Upgrade to unlock</a>}</div><div className="v42CustomizeGrid"><label>Density<select value={density} disabled={!paid} onChange={e=>save({density:e.target.value})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label>Dashboard layout<select value={layout} disabled={!paid} onChange={e=>save({layout:e.target.value})}><option value="classic">Classic</option><option value="focus">Focus</option><option value="research">Research first</option></select></label><label>Background area<select value={bgScope} disabled={!paid} onChange={e=>save({bgScope:e.target.value})}><option value="none">No background</option><option value="page">Whole page</option><option value="calendar">Calendar only</option></select></label></div>
 <h4>Background samples</h4><div className="v42BgSamples">{[["aurora","Aurora"],["cloud","Cloud"],["night","Night sky"],["paper","Soft paper"]].map(([v,l])=><button key={v} disabled={!paid} className={`${bgPreset===v?"selected":""} bg-${v}`} onClick={()=>save({bgPreset:v,bgImage:""})}><span>{l}</span></button>)}</div>
 <label className="v42Upload">Use your own image<input type="file" accept="image/*" disabled={!paid} onChange={e=>upload(e.target.files?.[0])}/><small>Stored on this device. Use an image you have the right to use.</small></label>{paid&&bgImage&&<button className="secondaryBtn" onClick={()=>save({bgImage:"",bgPreset:"none"})}>Remove uploaded background</button>}</section>
 </div>
}
