"use client";
import { useMemo, useState } from "react";
import type { FutureOrder, OrderStatus } from "@/lib/orders";
import type { FutureItem } from "@/lib/types";
export default function OrdersPanel({orders,tasks,onChange,onOpenTask}:{orders:FutureOrder[];tasks:FutureItem[];onChange:(orders:FutureOrder[])=>void;onOpenTask:(taskId:string)=>void}){
 const [adding,setAdding]=useState(false); const [title,setTitle]=useState(""); const [store,setStore]=useState(""); const [eta,setEta]=useState("");
 const sorted=useMemo(()=>[...orders].sort((a,b)=>new Date(b.orderedAt).getTime()-new Date(a.orderedAt).getTime()),[orders]);
 function update(id:string,status:OrderStatus){onChange(orders.map(o=>o.id===id?{...o,status}:o))}
 function add(){if(!title.trim())return;onChange([...orders,{id:crypto.randomUUID(),title:title.trim(),store:store.trim()||"Saved order",orderedAt:new Date().toISOString(),eta:eta||undefined,status:"ordered"}]);setTitle("");setStore("");setEta("");setAdding(false)}
 return <section className="v33PanelPage"><div className="v33PageIntro"><div><span>ORDERS & DELIVERIES</span><h3>Everything Future ordered for you</h3><p>Purchase details, delivery status, tracking and the task that created the order.</p></div><button className="v33Primary" onClick={()=>setAdding(v=>!v)}>+ Add order</button></div>
 {adding&&<div className="v33OrderForm"><input placeholder="Item" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="Store" value={store} onChange={e=>setStore(e.target.value)}/><input type="date" value={eta} onChange={e=>setEta(e.target.value)}/><button onClick={add}>Save</button></div>}
 <div className="v33OrderGrid">{sorted.length===0?<div className="v33EmptyState">No purchases recorded yet. Future will add approved purchases here.</div>:sorted.map(o=>{const task=tasks.find(t=>t.id===o.linkedTaskId);return <article key={o.id} className="v33OrderCard"><div className="v33OrderHead"><div><span>{o.store}</span><h4>{o.title}</h4></div><b className={`status-${o.status}`}>{o.status.replaceAll("_"," ")}</b></div><div className="v33OrderMeta"><span>Ordered <strong>{new Date(o.orderedAt).toLocaleDateString()}</strong></span><span>Arrival <strong>{o.eta?new Date(o.eta+"T12:00:00").toLocaleDateString():"—"}</strong></span>{o.price&&<span>Price <strong>{o.price}</strong></span>}{o.trackingNumber&&<span>Tracking <strong>{o.trackingNumber}</strong></span>}</div><div className="v33Progress"><i className="done"/><i className={o.status!=="ordered"?"done":""}/><i className={["out_for_delivery","delivered"].includes(o.status)?"done":""}/><i className={o.status==="delivered"?"done":""}/></div><div className="v33OrderActions"><select value={o.status} onChange={e=>update(o.id,e.target.value as OrderStatus)}><option value="ordered">Ordered</option><option value="shipped">Shipped</option><option value="out_for_delivery">Out for delivery</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select>{o.trackingUrl&&<a href={o.trackingUrl} target="_blank" rel="noreferrer">Track order ↗</a>}{task&&<button onClick={()=>onOpenTask(task.id)}>Open linked task</button>}</div></article>})}</div></section>
}
