"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Locale } from "@/lib/i18n";
import type { SearchPlace } from "@/components/SearchDiscover";

type RouteInfo={distanceKm:number;durationMin:number;steps:{instruction:string;distanceM:number}[]};

export default function PlaceMap({locale,initialPlace}:{locale:Locale;initialPlace?:SearchPlace|null}){
 const [place,setPlace]=useState(initialPlace?.title||""); const [selected,setSelected]=useState<SearchPlace|null>(initialPlace||null); const [coords,setCoords]=useState<{lat:number;lng:number}|null>(null); const [results,setResults]=useState<SearchPlace[]>([]); const [route,setRoute]=useState<RouteInfo|null>(null); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 useEffect(()=>{if(initialPlace){setSelected(initialPlace);setPlace(initialPlace.title);setResults([]);setRoute(null)}},[initialPlace]);
 const mapQuery=selected&&Number.isFinite(selected.lat)&&Number.isFinite(selected.lng)?`${selected.lat},${selected.lng}`:place||"Nice, France";
 const mapSrc=useMemo(()=>`https://www.google.com/maps?q=${encodeURIComponent(mapQuery)}&z=15&output=embed`,[mapQuery]);
 async function submit(e?:FormEvent){e?.preventDefault();if(!place.trim())return;setLoading(true);setMessage("");setRoute(null);try{const r=await fetch("/api/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({q:place.trim(),locale,kind:"place",lat:coords?.lat,lng:coords?.lng})});const d=await r.json();const rows=Array.isArray(d.results)?d.results.filter((x:SearchPlace)=>Number.isFinite(x.lat)&&Number.isFinite(x.lng)):[];setResults(rows);if(rows[0])setSelected(rows[0]);if(!rows.length)setMessage(locale==="th"?"ไม่พบสถานที่ที่ตรงคำค้น":"No matching place was found.")}catch{setMessage(locale==="th"?"ค้นหาสถานที่ไม่ได้ชั่วคราว":"Place search is temporarily unavailable.")}finally{setLoading(false)}}
 function nearMe(){if(!navigator.geolocation){setMessage(locale==="th"?"เบราว์เซอร์นี้ไม่รองรับตำแหน่ง":"Location is not available in this browser.");return}navigator.geolocation.getCurrentPosition(p=>{const next={lat:p.coords.latitude,lng:p.coords.longitude};setCoords(next);setMessage(locale==="th"?"ใช้ตำแหน่งปัจจุบันแล้ว":"Current location is ready.");if(selected)void calculateRoute(next,selected)},()=>setMessage(locale==="th"?"ไม่ได้รับอนุญาตให้ใช้ตำแหน่ง":"Location permission was not granted."),{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
 async function calculateRoute(origin=coords,destination=selected){if(!origin||!destination||!Number.isFinite(destination.lat)||!Number.isFinite(destination.lng)){setMessage(locale==="th"?"กด ‘ตำแหน่งของฉัน’ และเลือกสถานที่ก่อน":"Enable your location and select a place first.");return}setLoading(true);try{const r=await fetch("/api/places",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"route",origin,destination:{lat:destination.lat,lng:destination.lng}})});const d=await r.json();if(r.ok)setRoute(d);else setMessage(d.error||"Route unavailable")}catch{setMessage(locale==="th"?"คำนวณเส้นทางไม่ได้ชั่วคราว":"Route is temporarily unavailable.")}finally{setLoading(false)}}
 function directions(mode:"driving"|"walking"|"transit"|"bicycling"="driving"){if(!selected)return;const origin=coords?`${coords.lat},${coords.lng}`:"My Location";window.open(`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(`${selected.lat},${selected.lng}`)}&travelmode=${mode}`,"_blank","noopener,noreferrer")}
 return <section className="v32Card v41MapCard v47MapCard" id="map"><div className="v41MapHead"><div><strong>Map & Places</strong><small>{locale==="th"?"ค้นหาสถานที่ ดูระยะทาง เวลาเดินทาง และเปิดนำทาง":"Search places, calculate distance and travel time, then open navigation."}</small></div><button onClick={nearMe}>◎ {coords?(locale==="th"?"ตำแหน่งพร้อม":"Location ready"):(locale==="th"?"ตำแหน่งของฉัน":"My location")}</button></div><form className="v41MapSearch" onSubmit={submit}><span>⌖</span><input value={place} onChange={e=>setPlace(e.target.value)} placeholder={locale==="th"?"ค้นหาสถานที่ ร้านอาหาร โรงแรม สนามบิน...":"Search a place, restaurant, hotel, airport..."}/><button disabled={loading}>{loading?"…":locale==="th"?"ค้นหา":"Search"}</button></form>{message&&<div className="v32SearchMessage">{message}</div>}{results.length>1&&<div className="v47MapResults">{results.slice(0,5).map((r,i)=><button className={selected?.url===r.url?"active":""} key={`${r.url}-${i}`} onClick={()=>{setSelected(r);setRoute(null)}}><strong>{r.title}</strong><span>{r.address}{typeof r.distanceKm==="number"?` · ~${r.distanceKm} km`:""}</span></button>)}</div>}<iframe title="Place map" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={mapSrc}/><div className="v47DirectionsPanel"><div className="v47RouteSummary"><div><strong>{selected?.title||place||"Choose a place"}</strong><small>{selected?.address|| (coords?"Current location ready":"Use My location to calculate from where you are.")}</small></div>{route?<b>{route.durationMin} min · {route.distanceKm} km</b>:<button onClick={()=>calculateRoute()} disabled={!selected}>{locale==="th"?"คำนวณระยะทาง":"Calculate route"}</button>}</div><div className="v47TravelModes"><button onClick={()=>directions("driving")}>🚗</button><button onClick={()=>directions("walking")}>🚶</button><button onClick={()=>directions("transit")}>🚆</button><button onClick={()=>directions("bicycling")}>🚲</button><button className="primaryRoute" onClick={()=>directions("driving")} disabled={!selected}>{locale==="th"?"เริ่มนำทาง":"Start navigation"} ↗</button></div>{route&&route.steps.length>0&&<details className="v47Steps"><summary>{locale==="th"?"ดูวิธีเดินทางทีละขั้น":"Route steps"}</summary>{route.steps.map((s,i)=><div key={i}><span>{i+1}</span><p>{s.instruction}</p><b>{s.distanceM>=1000?`${(s.distanceM/1000).toFixed(1)} km`:`${s.distanceM} m`}</b></div>)}</details>}</div></section>
}
