"use client";
import { useMemo, useState } from "react";
import type { FutureItem, FutureItemType } from "@/lib/types";
import type { Locale } from "@/lib/i18n";
function keyOf(d:Date){return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`}
function dateOf(item:FutureItem){const r=item.startsAt??item.dueAt??item.remindAt;return r?new Date(r):null}
export default function SchedulePanel({items,selectedDate,locale,onAdd,onDelete,onComplete}:{items:FutureItem[];selectedDate:Date;locale:Locale;onAdd:(item:Omit<FutureItem,"id"|"createdAt">)=>void;onDelete:(id:string)=>void;onComplete:(id:string)=>void}){
 const [adding,setAdding]=useState(false); const [title,setTitle]=useState(""); const [time,setTime]=useState("09:00"); const [type,setType]=useState<FutureItemType>("task"); const lang=locale==="th"?"th-TH":locale==="fr"?"fr-FR":"en-US";
 const dayItems=useMemo(()=>items.filter(i=>{const d=dateOf(i);return d&&keyOf(d)===keyOf(selectedDate)&&!i.completedAt}).sort((a,b)=>(dateOf(a)?.getTime()??0)-(dateOf(b)?.getTime()??0)),[items,selectedDate]);
 function add(){if(!title.trim())return;const [h,m]=time.split(":").map(Number);const d=new Date(selectedDate);d.setHours(h||0,m||0,0,0);const iso=d.toISOString();onAdd({title:title.trim(),type,startsAt:type==="event"?iso:undefined,dueAt:type==="task"?iso:undefined,remindAt:type==="reminder"?iso:undefined,rawText:title.trim()});setTitle("");setAdding(false)}
 return <section className="v32Card v32Schedule" id="tasks"><div className="v32PanelHead"><div className="v32Title"><span className="v32Icon">☑</span><strong>Schedule & Tasks</strong></div><button className="v32PrimarySm" onClick={()=>setAdding(v=>!v)}>+ Add task</button></div><div className="v32SelectedDay"><strong>{selectedDate.toLocaleDateString(lang,{weekday:"short",day:"numeric",month:"short",year:"numeric"})}</strong><span>{dayItems.length} items</span></div>{adding&&<div className="v32InlineForm"><input placeholder="What needs to be done?" value={title} onChange={e=>setTitle(e.target.value)}/><div><input type="time" value={time} onChange={e=>setTime(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value as FutureItemType)}><option value="task">Task</option><option value="event">Event</option><option value="reminder">Reminder</option></select><button onClick={add}>Save</button></div></div>}<div className="v32ScheduleList">{dayItems.length===0?<div className="v32Empty">Nothing planned for this day.</div>:dayItems.map(item=>{const d=dateOf(item)!;return <article key={item.id}><button className="v32Check" onClick={()=>onComplete(item.id)}>□</button><time>{d.toLocaleTimeString(lang,{hour:"2-digit",minute:"2-digit"})}</time><span className={`v32ScheduleDot ${item.type}`}/><div><strong>{item.title}</strong><small>{item.type}</small></div><button className="v32More" onClick={()=>onDelete(item.id)}>×</button></article>})}</div><div className="v32Upcoming"><strong>Upcoming</strong>{items.filter(i=>{const d=dateOf(i);return d&&d>selectedDate&&!i.completedAt}).sort((a,b)=>(dateOf(a)?.getTime()??0)-(dateOf(b)?.getTime()??0)).slice(0,4).map(i=>{const d=dateOf(i)!;return <div key={i.id}><span>{d.toLocaleDateString(lang,{day:"numeric",month:"short"})}</span><b>{i.title}</b></div>})}</div></section>
}
