"use client";
import { FormEvent, useState } from "react";
import type { Locale } from "@/lib/i18n";

export type SearchPlace = { title:string; url:string; snippet?:string; source?:string; publishedAt?:string; lat?:number; lng?:number; address?:string; category?:string; distanceKm?:number };
type Source={name:string;title?:string;url?:string};
type SearchKind="general"|"place"|"news"|"shopping";

export default function SearchDiscover({locale,onOpenPlace}:{locale:Locale;onOpenPlace?:(place:SearchPlace)=>void}){
 const [q,setQ]=useState(""); const [answer,setAnswer]=useState(""); const [sources,setSources]=useState<Source[]>([]); const [results,setResults]=useState<SearchPlace[]>([]); const [kind,setKind]=useState<SearchKind>("general"); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(""); const [coords,setCoords]=useState<{lat:number;lng:number}|null>(null);
 async function search(e?:FormEvent,nextKind?:SearchKind){e?.preventDefault();if(!q.trim())return;const requested=nextKind||kind;setLoading(true);setMessage("");setAnswer("");setResults([]);try{const r=await fetch("/api/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({q:q.trim(),locale,kind:requested,lat:coords?.lat,lng:coords?.lng})});const d=await r.json();setAnswer(String(d.answer||d.error||""));setSources(Array.isArray(d.sources)?d.sources:[]);setResults(Array.isArray(d.results)?d.results:[]);setKind((d.kind||requested||"general") as SearchKind);if(d.freeMode)setMessage(locale==="th"?"ค้นหาฟรีจากข้อมูลเว็บ/แผนที่สาธารณะ และกรองผลลัพธ์ที่ไม่ตรงคำค้นออก":locale==="fr"?"Recherche gratuite via des sources publiques, avec filtrage de pertinence.":"Free public search with relevance filtering.");}catch{setMessage(locale==="th"?"การค้นหาขัดข้องชั่วคราว":"Search is temporarily unavailable.")}finally{setLoading(false)}}
 function useMyLocation(){if(!navigator.geolocation){setMessage(locale==="th"?"เบราว์เซอร์นี้ไม่รองรับตำแหน่ง":"Location is not supported in this browser.");return}navigator.geolocation.getCurrentPosition(p=>{setCoords({lat:p.coords.latitude,lng:p.coords.longitude});setMessage(locale==="th"?"ใช้ตำแหน่งปัจจุบันแล้ว — การค้นหาสถานที่จะคำนวณระยะใกล้เคียงให้":"Current location enabled for place distance.")},()=>setMessage(locale==="th"?"ไม่ได้รับอนุญาตให้ใช้ตำแหน่ง":"Location permission was not granted."),{enableHighAccuracy:false,timeout:8000})}
 function chooseKind(next:SearchKind){setKind(next); if(q.trim()) void search(undefined,next)}
 const placeholder=locale==="th"?"ค้นหาข้อมูล ข่าว สถานที่ สินค้า บุคคล...":locale==="fr"?"Rechercher informations, actualités, lieux, produits...":"Search information, news, places, products...";
 const isPlace=(r:SearchPlace)=>Number.isFinite(r.lat)&&Number.isFinite(r.lng);
 function directions(r:SearchPlace){const origin=coords?`${coords.lat},${coords.lng}`:"My Location";window.open(`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(`${r.lat},${r.lng}`)}`,"_blank","noopener,noreferrer")}
 return <section className="v32Card v41SearchOnly" id="search"><div className="v32SearchLeft"><div className="v32SearchHeading"><span className="v32BigSearch">⌕</span><div><strong>Search & Discover</strong><small>{locale==="th"?"ค้นหาเว็บ ข่าว และสถานที่ โดยไม่แสดงผลลัพธ์ที่ไม่ตรงคำค้น":"Free public-web search with relevance filtering."}</small></div></div><form className="v32SearchBar" onSubmit={search}><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder={placeholder}/><button disabled={loading}>{loading?(locale==="th"?"กำลังค้นหา…":"Searching…"):(locale==="th"?"ค้นหา":"Search")}</button></form><div className="v32SearchTabs"><button type="button" className={kind==="general"?"active":""} onClick={()=>chooseKind("general")}>All</button><button type="button" className={kind==="place"?"active":""} onClick={()=>chooseKind("place")}>Places</button><button type="button" className={kind==="news"?"active":""} onClick={()=>chooseKind("news")}>News</button><button type="button" className={kind==="shopping"?"active":""} onClick={()=>chooseKind("shopping")}>Shopping</button><button type="button" className="locationTab" onClick={useMyLocation}>◎ {coords?(locale==="th"?"ใช้ตำแหน่งแล้ว":"Location on"):(locale==="th"?"ตำแหน่งของฉัน":"My location")}</button></div>{message&&<div className="v32SearchMessage">{message}</div>}<div className="v33AnswerBox">{loading?<div className="v33AnswerLoading">Future is searching…</div>:<>{answer&&<><div className="v33AnswerLabel">FUTURE SEARCH · {kind.toUpperCase()}</div><div className="v33AnswerText">{answer}</div></>}{results.length>0&&<div className="v32Results">{results.map((x,i)=>isPlace(x)?<article className="v47PlaceResult" key={`${x.url}-${i}`}><div><strong>{x.title}</strong><span>{x.address||x.source||"OpenStreetMap"}{typeof x.distanceKm==="number"?` · ~${x.distanceKm} km`:""}</span>{x.snippet&&x.snippet!==x.address&&<p>{x.snippet}</p>}</div><div className="v47PlaceActions"><button onClick={()=>onOpenPlace?.(x)}>Map</button><button onClick={()=>directions(x)}>Directions ↗</button><a href={x.url} target="_blank" rel="noreferrer">Open</a></div></article>:<a key={`${x.url}-${i}`} href={x.url} target="_blank" rel="noreferrer"><strong>{x.title}</strong><span>{x.source||x.url}{x.publishedAt?` · ${x.publishedAt}`:""}</span>{x.snippet&&<p>{x.snippet}</p>}</a>)}</div>}{sources.length>0&&<div className="v33Sources"><span>Sources:</span>{sources.map((s,i)=><b key={`${s.name}-${i}`}>{s.name}</b>)}</div>}{!answer&&results.length===0&&<div className="v32SearchPlaceholder"><strong>{locale==="th"?"ค้นหาได้ฟรี":"Free search"}</strong><span>{locale==="th"?"ลอง “restaurants in Nice”, “ข่าว AI วันนี้”, “gift for mom under 50 euros”":"Try places, news, shopping or general information."}</span></div>}</>}</div></div></section>
}
