"use client";
import { FormEvent, useState } from "react";
import type { Locale } from "@/lib/i18n";

type Source={name:string;title?:string;url?:string};
type Result={title:string;url:string;snippet?:string;source?:string;publishedAt?:string};
export default function SearchDiscover({locale}:{locale:Locale}){
 const [q,setQ]=useState(""); const [answer,setAnswer]=useState(""); const [sources,setSources]=useState<Source[]>([]); const [results,setResults]=useState<Result[]>([]); const [kind,setKind]=useState("general"); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");
 async function search(e?:FormEvent){e?.preventDefault();if(!q.trim())return;setLoading(true);setMessage("");setAnswer("");setResults([]);try{const r=await fetch("/api/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({q:q.trim(),locale})});const d=await r.json();setAnswer(String(d.answer||d.error||""));setSources(Array.isArray(d.sources)?d.sources:[]);setResults(Array.isArray(d.results)?d.results:[]);setKind(String(d.kind||"general"));if(d.freeMode)setMessage(locale==="th"?"ค้นหาฟรีจากแหล่งข้อมูลสาธารณะ — ไม่ต้องใช้ OpenAI API Key":locale==="fr"?"Recherche gratuite via des sources publiques — aucune clé OpenAI requise.":"Free search from public sources — no OpenAI API key required.");else if(d.limited)setMessage(locale==="th"?"โหมดค้นหา AI ถึงขีดจำกัดแล้ว — ยังใช้การค้นหาฟรีได้":"AI research limit reached — free public search remains available.")}catch{setMessage(locale==="th"?"การค้นหาขัดข้องชั่วคราว":"Search is temporarily unavailable.")}finally{setLoading(false)}}
 const placeholder=locale==="th"?"ค้นหาข้อมูล ข่าว สถานที่ สินค้า บุคคล...":locale==="fr"?"Rechercher informations, actualités, lieux, produits...":"Search information, news, places, products...";
 return <section className="v32Card v41SearchOnly" id="search"><div className="v32SearchLeft"><div className="v32SearchHeading"><span className="v32BigSearch">⌕</span><div><strong>Search & Discover</strong><small>{locale==="th"?"ค้นหาข้อมูลบนเว็บแบบฟรี และให้ Future แสดงผลตรงนี้":"Free public-web search, with results shown directly in Future."}</small></div></div><form className="v32SearchBar" onSubmit={search}><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder={placeholder}/><button disabled={loading}>{loading?(locale==="th"?"กำลังค้นหา…":"Searching…"):(locale==="th"?"ค้นหา":"Search")}</button></form><div className="v32SearchTabs"><button type="button" onClick={()=>setQ("")}>All</button><button type="button" onClick={()=>setQ(locale==="th"?"ข่าวล่าสุด ":"latest news ")}>News</button><button type="button" onClick={()=>setQ(locale==="th"?"เปรียบเทียบสินค้า ":"compare products ")}>Shopping</button><button type="button" onClick={()=>setQ(locale==="th"?"อธิบายเรื่อง ":"explain ")}>Answers</button></div>{message&&<div className="v32SearchMessage">{message}</div>}<div className="v33AnswerBox">{loading?<div className="v33AnswerLoading">Future is searching…</div>:<>{answer&&<><div className="v33AnswerLabel">FUTURE SEARCH · {kind.toUpperCase()}</div><div className="v33AnswerText">{answer}</div></>}{results.length>0&&<div className="v32Results">{results.map((x,i)=><a key={`${x.url}-${i}`} href={x.url} target="_blank" rel="noreferrer"><strong>{x.title}</strong><span>{x.source||x.url}{x.publishedAt?` · ${x.publishedAt}`:""}</span>{x.snippet&&<p>{x.snippet}</p>}</a>)}</div>}{sources.length>0&&<div className="v33Sources"><span>Sources:</span>{sources.map((s,i)=><b key={`${s.name}-${i}`}>{s.name}</b>)}</div>}{!answer&&results.length===0&&<div className="v32SearchPlaceholder"><strong>{locale==="th"?"ค้นหาได้ฟรี":"Free search"}</strong><span>{locale==="th"?"เช่น “Nice สถานที่ท่องเที่ยว”, “ข่าว AI วันนี้”, “MacBook Air ราคา” — ไม่ต้องตั้งค่า OPENAI_API_KEY":"Try places, news, products or general facts. No OpenAI API key is required for standard search."}</span></div>}</>}</div></div></section>
}
