"use client";
import { useEffect, useState } from "react";
export default function WhatsAppPanel(){
 const [phone,setPhone]=useState(""); const [message,setMessage]=useState(""); const [business,setBusiness]=useState<{configured:boolean}>({configured:false}); const [status,setStatus]=useState("");
 useEffect(()=>{fetch("/api/whatsapp/status").then(r=>r.json()).then(d=>setBusiness({configured:Boolean(d.configured)})).catch(()=>{})},[]);
 function personal(){const digits=phone.replace(/[^0-9]/g,"");if(!digits){setStatus("Enter a phone number with country code.");return}window.open(`https://wa.me/${digits}?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")}
 async function sendBusiness(){if(!business.configured){setStatus("WhatsApp Business API is not configured in Vercel yet.");return}const r=await fetch("/api/whatsapp/send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({to:phone,message,approved:true})});const d=await r.json();setStatus(r.ok?"Message accepted by WhatsApp Business.":d.error||"Could not send.")}
 return <section className="v33PanelPage"><div className="v33PageIntro"><div><span>WHATSAPP</span><h3>Personal quick-send + Business automation</h3><p>Consumers can open their personal WhatsApp. Businesses can connect the official WhatsApp Business Platform for API messaging.</p></div><div className={`v33ConnectionBadge ${business.configured?"ready":""}`}>{business.configured?"Business API ready":"Business API not configured"}</div></div>
 <div className="v33WhatsGrid"><article><h4>Personal WhatsApp</h4><p>Open a chat in the WhatsApp app/web. This does not give Future access to your private inbox.</p><label>Phone with country code<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="33612345678"/></label><label>Message<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a message…"/></label><button className="v33Primary" onClick={personal}>Open WhatsApp ↗</button></article><article><h4>WhatsApp Business</h4><p>Use Meta’s official Business Platform for automated send/receive workflows, approvals and customer service.</p><div className="v33EnvList"><code>WHATSAPP_ACCESS_TOKEN</code><code>WHATSAPP_PHONE_NUMBER_ID</code><code>WHATSAPP_VERIFY_TOKEN</code></div><button className="v33Primary" onClick={sendBusiness}>Send approved test</button><small>Production receiving requires a Meta webhook URL.</small></article></div>{status&&<div className="v33Status">{status}</div>}</section>
}
