import { NextRequest, NextResponse } from "next/server";
import { createServerSupabase } from "@/lib/supabase/server";
import { estimateOpenAICost, getUsageAccess, recordUsage } from "@/lib/usage";

type Result={title:string;url:string;snippet?:string;source?:string;publishedAt?:string};

function extractText(data:any){if(typeof data?.output_text==="string")return data.output_text;for(const item of data?.output??[])for(const part of item?.content??[])if(part?.type==="output_text"&&typeof part.text==="string")return part.text;return ""}
function safeJson(text:string){const clean=text.trim().replace(/^```(?:json)?/i,"").replace(/```$/i,"").trim();return JSON.parse(clean)}
function webCalls(data:any){return (Array.isArray(data?.output)?data.output:[]).filter((x:any)=>String(x?.type||"").includes("web_search")).length;}
function decodeHtml(s:string){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]*>/g," ").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&nbsp;/g," ").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/\s+/g," ").trim()}
function uniq(xs:Result[]){const seen=new Set<string>();return xs.filter(x=>{const key=x.url.replace(/\/$/,"");if(!key||seen.has(key))return false;seen.add(key);return true})}
function unwrapDuckUrl(raw:string){try{const u=new URL(raw.startsWith("//")?`https:${raw}`:raw,"https://duckduckgo.com");const uddg=u.searchParams.get("uddg");return uddg?decodeURIComponent(uddg):u.href}catch{return raw}}

const STOP=new Set(["the","a","an","and","or","of","for","to","in","on","at","is","are","with","from","under","latest","best","find","show","me","news","search","what","where","how","de","du","des","le","la","les","et","ou","pour","dans","sur","à","au","aux","un","une","en","ล่าสุด","หา","ค้นหา","ข้อมูล","ที่","ใน","ของ","และ","ให้","ฉัน"]);
function words(s:string){return s.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^\p{L}\p{N}€$£]+/gu," ").split(/\s+/).filter(Boolean)}
function keyWords(s:string){return words(s).filter(w=>w.length>1&&!STOP.has(w))}
function intentOf(q:string){const s=q.toLowerCase();if(/\b(news|headline|breaking|today|latest|actualité|actualites|nouvelles|ข่าว)\b/.test(s))return "news";if(/\b(restaurant|cafe|hotel|bar|museum|place|near|nearby|in nice|à nice|a nice|location|address|เที่ยว|ร้าน|โรงแรม|สถานที่)\b/.test(s))return "place";if(/\b(buy|price|shop|shopping|gift|deal|compare|under\s*[€$£]?\s*\d+|cadeau|prix|acheter|ของขวัญ|ราคา|ซื้อ|สินค้า)\b/.test(s))return "shopping";if(/\b(flight|train|trip|travel|booking|voyage|vol|เที่ยวบิน|เดินทาง)\b/.test(s))return "travel";return "general"}
function locationHint(q:string){const m=q.match(/(?:\bin\b|\bnear\b|\bà\b|\ba\b|\bใน\b|\bที่\b)\s+([\p{L}][\p{L}\-' ]{1,40})/iu);if(!m)return "";return m[1].split(/\b(?:for|under|with|today|now|open|ราคา|สำหรับ)\b/i)[0].trim().split(/[,.;]/)[0].trim()}
function scoreResult(r:Result,q:string,intent:string,location:string){const hay=words(`${r.title} ${r.snippet||""} ${r.url}`).join(" ");const keys=keyWords(q);let score=0;for(const k of keys){if(hay.includes(k))score+=2;}if(location){const lk=words(location).join(" ");if(lk&&hay.includes(lk))score+=8;else if(intent==="place")score-=7;}const host=(()=>{try{return new URL(r.url).hostname}catch{return ""}})();if(intent==="news"&&/(reuters|apnews|bbc|france24|lemonde|theguardian|cnn|nytimes|techcrunch|theverge|arstechnica|wired|news\.google)/i.test(host))score+=4;if(intent==="shopping"&&/(amazon|etsy|fnac|darty|cdiscount|ikea|sephora|decathlon|zalando|ebay|idealo)/i.test(host))score+=3;if(/wikipedia/i.test(host)&&intent!=="general")score-=5;return score}
function rank(xs:Result[],q:string,intent:string,location:string){return uniq(xs).map(x=>({x,s:scoreResult(x,q,intent,location)})).sort((a,b)=>b.s-a.s).filter((v,i)=>v.s>0||i<3).map(v=>v.x).slice(0,10)}

async function bingRssSearch(q:string){const out:Result[]=[];try{const r=await fetch(`https://www.bing.com/search?format=rss&q=${encodeURIComponent(q)}`,{cache:"no-store",headers:{"User-Agent":"Mozilla/5.0 Future-AI-Secretary/4.6","Accept":"application/rss+xml,application/xml,text/xml,*/*","Accept-Language":"fr-FR,fr;q=0.9,en;q=0.8"}});if(!r.ok)return out;const xml=await r.text();const items=xml.match(/<item>[\s\S]*?<\/item>/gi)||[];for(const item of items.slice(0,12)){const title=decodeHtml(item.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||"");const url=decodeHtml(item.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||"");const snippet=decodeHtml(item.match(/<description>([\s\S]*?)<\/description>/i)?.[1]||"");if(title&&/^https?:\/\//i.test(url))out.push({title,url,snippet:snippet.slice(0,420),source:"Bing"});}}catch{}return out}

async function duckHtmlSearch(q:string){const out:Result[]=[];try{const r=await fetch("https://html.duckduckgo.com/html/",{method:"POST",cache:"no-store",headers:{"User-Agent":"Mozilla/5.0 Future-AI-Secretary/4.6","Content-Type":"application/x-www-form-urlencoded","Accept-Language":"fr-FR,fr;q=0.9,en;q=0.8"},body:new URLSearchParams({q}).toString()});if(!r.ok)return out;const html=await r.text();const blocks=html.match(/<div[^>]+class="[^"]*result[^"]*"[^>]*>[\s\S]*?(?=<div[^>]+class="[^"]*result[^"]*"|<div[^>]+class="nav-link|<\/body>)/gi)||[];for(const block of blocks.slice(0,12)){const a=block.match(/<a[^>]+class="[^"]*result__a[^"]*"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;const url=unwrapDuckUrl(decodeHtml(a[1]));const title=decodeHtml(a[2]);const sn=block.match(/class="[^"]*result__snippet[^"]*"[^>]*>([\s\S]*?)<\/(?:a|div)/i);const snippet=decodeHtml(sn?.[1]||"");if(title&&/^https?:\/\//i.test(url))out.push({title,url,snippet:snippet.slice(0,420),source:"DuckDuckGo"});}}catch{}return out}

async function googleNewsSearch(q:string,locale:string){const out:Result[]=[];try{const conf=locale==="fr"?{hl:"fr",gl:"FR",ceid:"FR:fr"}:locale==="th"?{hl:"th",gl:"TH",ceid:"TH:th"}:{hl:"en",gl:"US",ceid:"US:en"};const url=`https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=${conf.hl}&gl=${conf.gl}&ceid=${encodeURIComponent(conf.ceid)}`;const r=await fetch(url,{cache:"no-store",headers:{"User-Agent":"Mozilla/5.0 Future-AI-Secretary/4.6"}});if(!r.ok)return out;const xml=await r.text();for(const item of (xml.match(/<item>[\s\S]*?<\/item>/gi)||[]).slice(0,12)){const title=decodeHtml(item.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||"");const link=decodeHtml(item.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||"");const publishedAt=decodeHtml(item.match(/<pubDate>([\s\S]*?)<\/pubDate>/i)?.[1]||"");const source=decodeHtml(item.match(/<source[^>]*>([\s\S]*?)<\/source>/i)?.[1]||"Google News");if(title&&/^https?:\/\//.test(link))out.push({title,url:link,source,publishedAt,snippet:publishedAt?`Published ${publishedAt}`:""});}}catch{}return out}

async function wikipediaSearch(q:string,locale:string){const lang=locale==="th"?"th":locale==="fr"?"fr":"en";const results:Result[]=[];let answer="";try{const wr=await fetch(`https://${lang}.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(q)}&srlimit=5&utf8=1&format=json&origin=*`,{cache:"no-store",headers:{"User-Agent":"Future-AI-Secretary/4.6"}});if(wr.ok){const w=await wr.json();const items=Array.isArray(w?.query?.search)?w.query.search:[];for(const it of items){const url=`https://${lang}.wikipedia.org/wiki/${encodeURIComponent(String(it.title).replace(/ /g,"_"))}`;results.push({title:String(it.title),url,snippet:decodeHtml(String(it.snippet||"")),source:"Wikipedia"});}const qKeys=keyWords(q);const first=items[0];const titleKeys=first?keyWords(String(first.title)):[];const relevant=titleKeys.some(k=>qKeys.includes(k));if(first&&relevant){const sr=await fetch(`https://${lang}.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(String(first.title))}`,{cache:"no-store",headers:{"User-Agent":"Future-AI-Secretary/4.6"}});if(sr.ok){const d=await sr.json();answer=String(d?.extract||"").slice(0,800)}}}}catch{}return {results,answer}}

function searchVariants(q:string,intent:string,location:string){const year=new Date().getFullYear();if(intent==="news")return [`${q} ${year}`,q];if(intent==="place"&&location)return [`${q} ${location} France`,`${q} site:tripadvisor.com OR site:thefork.fr OR site:guide.michelin.com`,q];if(intent==="shopping")return [`${q} France EUR`,`${q} buy price France`,q];if(intent==="travel")return [`${q} France travel`,q];return [q]}

function fallbackLinks(q:string,intent:string,locale:string){const lang=locale==="fr"?"fr":locale==="th"?"th":"en";const out:Result[]=[{title:locale==="th"?"ค้นหาคำนี้บน Google":"Search this query on Google",url:`https://www.google.com/search?q=${encodeURIComponent(q)}&hl=${lang}`,source:"Google"},{title:locale==="th"?"ค้นหาคำนี้บน Bing":"Search this query on Bing",url:`https://www.bing.com/search?q=${encodeURIComponent(q)}`,source:"Bing"}];if(intent==="place")out.unshift({title:locale==="th"?"ดูสถานที่นี้บน Google Maps":"Open this place search in Google Maps",url:`https://www.google.com/maps/search/${encodeURIComponent(q)}`,source:"Google Maps"});return out}

async function freePublicSearch(q:string,locale:string){const intent=intentOf(q);const location=locationHint(q);if(intent==="news"){const news=await googleNewsSearch(q,locale);const results=rank(news,q,intent,location);const answer=results.length?(locale==="th"?`พบข่าวล่าสุด ${results.length} รายการสำหรับ “${q}” เรียงจากแหล่งข่าวปัจจุบันด้านล่าง`:`Found ${results.length} current news result(s) for “${q}”.`):(locale==="th"?"ยังดึงข่าวล่าสุดไม่ได้ในครั้งนี้ ใช้ลิงก์ค้นหาสำรองด้านล่างได้เลย":"Current news results were unavailable this time. Use the fallback search links below.");return {answer,results:results.length?results:fallbackLinks(q,intent,locale),sources:[...new Set(results.map(x=>x.source||"News"))].slice(0,6).map(name=>({name})),kind:intent,freeMode:true}}
 const variants=searchVariants(q,intent,location);const batches=await Promise.all(variants.slice(0,3).flatMap(v=>[bingRssSearch(v),duckHtmlSearch(v)]));let combined=batches.flat();let wiki={results:[] as Result[],answer:""};if(intent==="general")wiki=await wikipediaSearch(q,locale);combined=[...combined,...wiki.results];let results=rank(combined,q,intent,location);if(intent==="place"&&location){const strict=results.filter(r=>words(`${r.title} ${r.snippet||""} ${r.url}`).includes(words(location)[0]||""));if(strict.length>=2)results=strict.slice(0,10)}
 const sources=[...new Set(results.map(x=>{try{return new URL(x.url).hostname.replace(/^www\./,"")}catch{return x.source||"Web"}}))].slice(0,6).map(name=>({name}));let answer="";if(intent==="general"&&wiki.answer)answer=wiki.answer;else if(results.length)answer=locale==="th"?`พบ ${results.length} ผลลัพธ์ที่เกี่ยวข้องสำหรับ “${q}” และจัดลำดับตามคำค้น${location?` โดยเน้น ${location}`:""}`:locale==="fr"?`${results.length} résultats pertinents trouvés pour « ${q} »${location?`, avec priorité à ${location}`:""}.`:`Found ${results.length} relevant results for “${q}”${location?`, prioritizing ${location}`:""}.`;
 if(!results.length){results=fallbackLinks(q,intent,locale);answer=locale==="th"?"แหล่งค้นหาฟรีไม่ส่งผลลัพธ์ที่น่าเชื่อถือพอในครั้งนี้ จึงไม่แสดงข้อมูลที่อาจผิด และให้ลิงก์ค้นหาตรงแทน":"The free providers did not return sufficiently relevant results, so Future is showing direct search fallbacks instead of potentially wrong information."}
 return {answer,results,sources,kind:intent,freeMode:true};}

export async function POST(req:NextRequest){
 const body=await req.json().catch(()=>null);const q=typeof body?.q==="string"?body.q.trim():"";const locale=["th","fr","en"].includes(body?.locale)?body.locale:"en";if(!q)return NextResponse.json({answer:"",sources:[],results:[]});
 const apiKey=process.env.OPENAI_API_KEY;const supabase=await createServerSupabase();let userId:string|undefined;let plan="free";let usage:any=null;if(supabase){const {data:{user}}=await supabase.auth.getUser();userId=user?.id;}if(userId){usage=await getUsageAccess(userId);plan=usage.plan||"free";}
 const useAi=Boolean(apiKey&&userId&&plan!=="free"&&usage&&usage.webSearches<usage.limits.webSearches);
 if(useAi){try{const model=process.env.OPENAI_MODEL||"gpt-5.6-luna";const base:any={model,instructions:`You are Future Search. Search the public web and answer directly inside the app. Return JSON only: {"answer":"clear useful answer in ${locale}","sources":[{"name":"publisher/domain","title":"source title"}],"kind":"general|place|news|shopping|travel"}. Respect the user's exact place, budget and freshness intent. Never silently substitute a different city or topic. Use current information when relevant and distinguish uncertainty.`,input:q,max_output_tokens:1800};let r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${apiKey}`},body:JSON.stringify({...base,tools:[{type:"web_search"}]})});if(!r.ok)r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${apiKey}`},body:JSON.stringify(base)});if(r.ok){const data=await r.json();const parsed=safeJson(extractText(data));const wc=Math.max(1,webCalls(data));const input=Number(data?.usage?.input_tokens||0),output=Number(data?.usage?.output_tokens||0);if(userId){await recordUsage({userId,kind:"ai_message",model,inputTokens:input,outputTokens:output,estimatedCostUsd:estimateOpenAICost(input,output,0),metadata:{surface:"search"}});await recordUsage({userId,kind:"web_search",model,estimatedCostUsd:estimateOpenAICost(0,0,wc),metadata:{surface:"search",count:wc}});}return NextResponse.json({answer:String(parsed?.answer||""),sources:Array.isArray(parsed?.sources)?parsed.sources.slice(0,6):[],results:[],kind:parsed?.kind||intentOf(q),freeMode:false})}}catch{}}
 return NextResponse.json(await freePublicSearch(q,locale));
}
